import os
import re
import datetime

base_path = "/Users/daniel/Documents/AGY/agy_pmt/05_project_pmt/project_ai_betting_framework/06_Automated_Models"
leaderboard_path = os.path.join(base_path, "Model_Leaderboard.md")

dirs = {
    "Graduated_Strategies": "Graduated",
    "Ready_For_Backtesting": "Ready For Backtest",
    "Active_Strategies": "Ready For Backtest",
    "Ideation_Crucible": "In Crucible",
    "Archived_Strategies": "Archived"
}

models = []

for dir_name, status in dirs.items():
    dir_path = os.path.join(base_path, dir_name)
    if not os.path.exists(dir_path): continue
    for f in os.listdir(dir_path):
        if not f.endswith(".md"): continue
        if "_07_Presentation_Deck" in f: continue
        
        match = re.search(r'Model_(\d+)', f)
        if not match: continue
        model_id = int(match.group(1))
        
        raw_name = f.replace(".md", "")
        # Remove the Model_XX_ prefix for the clean name
        name_clean = re.sub(r'^Model_\d+_', '', raw_name).replace("_", " ")
        
        mtime = os.path.getmtime(os.path.join(dir_path, f))
        date_moved = datetime.datetime.fromtimestamp(mtime).strftime('%Y-%m-%d')
        
        roi, clv, win, feas, prac, comp = "Pending", "Pending", "Pending", "Pending", "Pending", "Pending"
        strategy_str, efficiency_str, takeaway_str = "", "", ""
        
        with open(os.path.join(dir_path, f), 'r') as file:
            content = file.read()
            
            feas_m = re.search(r'\*?\*?Feasibility:\*?\*?\s*(\d+)/10', content, re.IGNORECASE)
            if feas_m: feas = feas_m.group(1)
            
            prac_m = re.search(r'\*?\*?Practicality:\*?\*?\s*(\d+)/10', content, re.IGNORECASE)
            if prac_m: prac = prac_m.group(1)

            if status == "Graduated":
                roi_m = re.search(r'ROI:\s*([0-9.%+-]+)', content)
                if roi_m: 
                    roi_val = roi_m.group(1)
                    if "%" in roi_val:
                        try:
                            num = float(roi_val.replace("%", "").replace(",", ""))
                            roi = f"{num/100:.1f}x"
                        except:
                            roi = roi_val
                    else:
                        roi = roi_val
                
                clv_m = re.search(r'CLV Beat Rate:\s*([0-9.%]+)', content)
                if clv_m: clv = clv_m.group(1)
                
                win_m = re.search(r'Win Rate:\s*([0-9.%]+)', content)
                if win_m: win = win_m.group(1)
                
                comp_m = re.search(r'\*\*Composite Score:\*\*\s*(\d+)/100', content)
                if comp_m: comp = comp_m.group(1)
                
            elif status == "Archived":
                roi, clv, win, feas, prac, comp = "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"

            concept_m = re.search(r'\*\*Concept:\*\*\s*\n?(.*?)(?=\n\*|\n\n|\n\*\*|\Z)', content, re.DOTALL)
            if concept_m:
                bluf_raw = concept_m.group(1).strip()
                bluf_raw = bluf_raw.replace("**", "") # Strip bolding
                
                # Parse out the 3 sections generated by the Penny subagents
                parts = re.search(r'Strategy:\s*(.*?)\s*Efficiency:\s*(.*?)\s*Key Takeaway:\s*(.*)', bluf_raw, re.IGNORECASE | re.DOTALL)
                if parts:
                    s_raw = parts.group(1).strip()
                    e_raw = parts.group(2).strip()
                    t_raw = parts.group(3).strip()
                    
                    # Format Strategy as a single clean paragraph (preserving internal hyphens)
                    strategy_str = s_raw.replace("\n", " ")
                    strategy_str = re.sub(r'(?:^|\s)\(\d+\)\s*', ' ', strategy_str)
                    strategy_str = re.sub(r'(?:^|\s)\d+[\.)]\s*', ' ', strategy_str)
                    strategy_str = re.sub(r'(?:^|\s)[-*••]\s+', ' ', strategy_str)
                    strategy_str = re.sub(r'\s+', ' ', strategy_str).strip()
                    
                    # Format Efficiency as a clean vertical numbered list (1), (2), (3)
                    e_clean = e_raw.replace("\n", " ")
                    e_clean = re.sub(r'\s+', ' ', e_clean)
                    e_parts = []
                    for p in re.split(r'[,;]', e_clean):
                        p_clean = re.sub(r'^[-*•]\s*', '', p.strip())
                        p_clean = re.sub(r'^\(\d+\)\s*', '', p_clean)
                        p_clean = re.sub(r'^\d+[\.)]\s*', '', p_clean)
                        p_clean = p_clean.strip()
                        if p_clean:
                            e_parts.append(p_clean)
                    
                    if e_parts:
                        efficiency_str = "<br>".join(f"({idx+1}) {part}" for idx, part in enumerate(e_parts))
                    else:
                        efficiency_str = "N/A"
                        
                    takeaway_str = t_raw.replace("\n", " ")
                    takeaway_str = re.sub(r'\s+', ' ', takeaway_str).strip()
                else:
                    # FALLBACK LOGIC: Strategy gets the entire concept block, others set to N/A
                    strategy_str = bluf_raw.replace("\n", " ")
                    strategy_str = re.sub(r'(?:^|\s)\(\d+\)\s*', ' ', strategy_str)
                    strategy_str = re.sub(r'(?:^|\s)\d+[\.)]\s*', ' ', strategy_str)
                    strategy_str = re.sub(r'(?:^|\s)[-*••]\s+', ' ', strategy_str)
                    strategy_str = re.sub(r'\s+', ' ', strategy_str).strip()
                    
                    efficiency_str = "N/A"
                    takeaway_str = "N/A"
            
            if status in ["In Crucible", "Ready For Backtest"]:
                if feas.isdigit() and prac.isdigit():
                    # Calculate a pre-test composite score purely from Feasibility and Practicality
                    comp = str((int(feas) + int(prac)) * 5)

        models.append({
            "id": model_id,
            "name": f.replace(".md", ""),
            "status": status,
            "roi": roi,
            "clv": clv,
            "win": win,
            "feas": feas,
            "prac": prac,
            "comp": comp,
            "strategy": strategy_str,
            "efficiency": efficiency_str,
            "takeaway": takeaway_str,
            "date_moved": date_moved,
            "clean_name": name_clean
        })

def get_score_val(val):
    return int(val) if str(val).isdigit() else 0

def sort_key(m):
    if m['status'] == 'Graduated':
        comp_val = get_score_val(m['comp'])
        return (0, -comp_val)
    elif m['status'] == 'Ready For Backtest': 
        feas = get_score_val(m['feas'])
        prac = get_score_val(m['prac'])
        return (1, -(feas + prac), m['id'])
    elif m['status'] == 'In Crucible': 
        feas = get_score_val(m['feas'])
        prac = get_score_val(m['prac'])
        return (2, -(feas + prac), m['id'])
    else: 
        return (3, m['id'])

models.sort(key=sort_key)

unique_models = []
seen = set()
for m in models:
    if m['id'] not in seen:
        seen.add(m['id'])
        unique_models.append(m)

with open(leaderboard_path, 'w') as f:
    f.write("# Quant Portfolio Leaderboard\n\n")
    f.write("*This leaderboard tracks the entire lifecycle of all automated strategies across the PMT framework. It is autonomously maintained by the Quant-Prime and Quant-Validator agents.*\n\n")
    # Split into 3 columns instead of BLUF & Takeaways
    f.write("| Rank | Model ID | Name | Strategy | Efficiency | Key Takeaway | Status | ROI | CLV Beat | Win Rate | Feas. | Prac. | Comp. Score | Date Moved |\n")
    f.write("| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n")
    
    for idx, m in enumerate(unique_models):
        rank = str(idx + 1) if m['status'] == 'Graduated' else "-"
        model_id = f"M-{m['id']:03d}"
        
        f.write(f"| {rank} | {model_id} | {m['clean_name']} | {m['strategy']} | {m['efficiency']} | {m['takeaway']} | {m['status']} | {m['roi']} | {m['clv']} | {m['win']} | {m['feas']} | {m['prac']} | {m['comp']} | {m['date_moved']} |\n")

    f.write("\n---\n")
    f.write("*(Updated dynamically by PMT Agents)*\n")

print("Leaderboard generation complete.")
