/**
 * @file 05_StrategicReviews.js
 * @description Multi-Cadence Strategic Review Pipelines: 7-Day Weekly Roadmap, 28-Day Strategic Pruning & 84-Day Quarterly Reflection.
 */

// ==========================================
// SECTION 1: 7-DAY WEEKLY ROADMAP PIPELINE
// ==========================================

/**
 * @file src/Code_WeeklyReview.js
 * @description Generates the 7-Day Roadmap by sweeping the backlog and aligning with weekly calendar capacity.
 */

function runWeeklyReview() {
  const importerListId = SYSTEM_CONFIG.TASKS.IMPORTER_LIST_ID;
  const todoListId = SYSTEM_CONFIG.TASKS.TODO_LIST_ID;
  const recurringListId = SYSTEM_CONFIG.TASKS.RECURRING_LIST_ID;
  
  const rawTasks = [];
  [importerListId, todoListId, recurringListId].forEach(listId => {
    let pageToken;
    do {
      try {
        const response = Tasks.Tasks.list(listId, { showCompleted: false, showHidden: false, showAssigned: true, maxResults: 100, pageToken: pageToken });
        const items = response.items || [];
        items.forEach(t => rawTasks.push({ id: t.id, title: t.title, due: t.due, notes: t.notes || "", status: t.status }));
        pageToken = response.nextPageToken;
      } catch (e) {
        console.error(`runWeeklyReview Error reading list ${listId}: ${e.message}`);
        pageToken = undefined;
      }
    } while (pageToken);
  });

  if (rawTasks.length === 0) {
     console.error("runWeeklyReview: No tasks found. Aborting to prevent generating an empty plan.");
     return;
  }

  const payload = {
    currentTime: new Date().toISOString(),
    capacity7Days: getCalendarCapacity7Days(),
    goals: getSystemGoals(),
    allTasksContext: rawTasks.map(t => {
       const parsed = parseTaskNotes(t.notes);
       let metadata = parsed.metadata || {};
       let cleanNotes = parsed.baseNotes.replace(/\[DEADLINE:[^\]]*\]\s*\|\s*\[DURATION:[^\]]*\]\s*\|\s*\[GOAL:[^\]]*\]/g, "");
       cleanNotes = cleanNotes.replace(/\[DURATION:[^\]]*\]\s*\|\s*\[GOAL:[^\]]*\]/g, "");
       return { 
         id: t.id,
         title: t.title, 
         due: t.due, 
         notes: cleanNotes.trim(),
         category_path: metadata.category_path || "N/A",
         goal: metadata.goal || "N/A",
         duration: metadata.duration || "N/A"
       };
    })
  };

  let systemPrompt = "";
  try {
     const fileId = SYSTEM_CONFIG.DOCS.TASK_MASTER_WEEKLY_PROMPT_ID;
     if (!fileId) throw new Error("TASK_MASTER_WEEKLY_PROMPT_ID is not configured in SYSTEM_CONFIG.");
     const file = DriveApp.getFileById(fileId);
     systemPrompt = processPromptText(file.getBlob().getDataAsString());
  } catch(e) {
     console.error("Failed to load 7-Day prompt from Drive:", e.message);
     return;
  }
  
  const payloadStr = JSON.stringify(payload);
  // Use 3.7 Flash for hybrid reasoning, fallback to Pro then Flash Lite if needed
  const modelsToTry = [
    SYSTEM_CONFIG.SECRETS.GEMINI_MODEL_PRO, 
    SYSTEM_CONFIG.SECRETS.GEMINI_MODEL_FALLBACK_PRO || "gemini-pro-latest", 
    SYSTEM_CONFIG.SECRETS.GEMINI_MODEL_FLASH_LITE
  ];
  
  let result = null;
  let finalModelUsed = modelsToTry[0];
  
  for (const currentModel of modelsToTry) {
    if (!currentModel) continue;
    finalModelUsed = currentModel;
    console.log(`Executing 7-Day Review via ${currentModel}...`);
    
    result = callGemini(payloadStr, currentModel, systemPrompt, null, true);
    if (!result.error) {
      break;
    }
    console.warn(`7-Day Review failed with ${currentModel}:`, result.error);
  }

  if (!result || result.error) {
      console.error("7-Day Review failed after all attempts.");
      return;
  }
  
  let markdownReport = result.text;
  const timestamp = new Date().toLocaleString("en-GB", { timeZone: "Europe/London" });
  markdownReport += `\n\n---\n*Report dynamically generated by ${finalModelUsed} on ${timestamp}*`;
  
  write7DayRoadmap(markdownReport);
  console.log("7-Day Review Complete. Roadmap generated.");
}

function getCalendarCapacity7Days() {
  const calendarId = "primary";
  const now = new Date();
  const nextWeek = new Date(now.getTime() + (7 * 24 * 60 * 60 * 1000));
  
  try {
    const capacityMap = {};
    for (let i = 0; i < 7; i++) {
      const d = new Date(now.getTime() + (i * 24 * 60 * 60 * 1000));
      const dateKey = Utilities.formatDate(d, "Europe/London", "yyyy-MM-dd");
      capacityMap[dateKey] = { busyHours: 0, availableHours: 12 };
    }
    
    let pageToken;
    do {
      const response = Calendar.Events.list(calendarId, {
        timeMin: now.toISOString(),
        timeMax: nextWeek.toISOString(),
        singleEvents: true,
        maxResults: 250,
        pageToken: pageToken
      });
      
      const items = response.items || [];
      items.forEach(e => {
        // Skip Free events and All-Day events
        if (e.transparency === 'transparent') return;
        if (e.start.date) return; // All-day events only have a date, not dateTime
        
        const startTime = new Date(e.start.dateTime);
        const endTime = new Date(e.end.dateTime);
        const durationHours = (endTime - startTime) / (1000 * 60 * 60);
        const dateKey = Utilities.formatDate(startTime, "Europe/London", "yyyy-MM-dd");
        
        if (capacityMap[dateKey]) {
          capacityMap[dateKey].busyHours += durationHours;
          capacityMap[dateKey].availableHours = Math.max(0, 12 - capacityMap[dateKey].busyHours);
        }
      });
      pageToken = response.nextPageToken;
    } while (pageToken);
    
    return capacityMap;
  } catch (e) {
    console.error("Failed to fetch calendar capacity: " + e.message);
    return { error: "Failed to fetch calendar capacity" };
  }
}

function write7DayRoadmap(markdownStr) {
  const rootFolderId = SYSTEM_CONFIG.ROOTS.WORKSPACE_FOLDER_ID;
  const suffix = IS_CE_ENV ? " (CE)" : " (Private)";
  const fileName = `TS - Task Master > 7 Day Roadmap${suffix}.md`;
  try {
     const rootFolder = DriveApp.getFolderById(rootFolderId);
     const exportFolders = rootFolder.getFoldersByName("exports");
     const folder = exportFolders.hasNext() ? exportFolders.next() : rootFolder;
     const files = folder.getFilesByName(fileName);
     let file;
     if (files.hasNext()) {
        file = files.next();
        file.setContent(markdownStr);
     } else {
        file = folder.createFile(fileName, markdownStr, MimeType.PLAIN_TEXT);
     }
     return file.getUrl();
  } catch(e) {
     console.error("Failed to write 7-Day Roadmap:", e.message);
     return null;
  }
}

function weeklyReviewTriggerWrapper() {
  const lock = LockService.getScriptLock();
  if (!lock.tryLock(10000)) {
    console.warn("Could not acquire script lock. Weekly review is likely running.");
    return;
  }
  try {
    const currentDay = new Date().getDay(); // 0 is Sunday, 5 is Friday
    // Execute only on Sunday at 9:00
    const currentHour = new Date().getHours();
    
    if (currentDay === 0 && [9].includes(currentHour)) {
      console.log("Executing weekly 7-Day Review...");
      runWeeklyReview();
    } else {
      console.log(`Skipping weekly review (Day: ${currentDay}, Hour: ${currentHour}).`);
    }
  } finally {
    lock.releaseLock();
  }
}


// ==========================================
// SECTION 2: 28-DAY MONTHLY STRATEGIC PRUNING
// ==========================================

/**
 * @file src/Code_28DayReview.js
 * @description Generates the 28-Day Strategic Pruning Report by aggressively pruning the backlog and aligning tasks with overarching goals.
 *
 * @version 1.0.0
 * @last_modified 2024-07-28
 * @modified_by Jules
 *
 * @changelog
 * - 1.0.0: Added standardized JSDoc headers and variable naming.
 */

/**
 * Generates the 28-Day Strategic Pruning Report by aggregating tasks,
 * calling the AI model for review, and saving the output to Google Drive.
 *
 * @returns {void}
 */
function runMonthlyReview() {
  const importerListId = SYSTEM_CONFIG.TASKS.IMPORTER_LIST_ID;
  const todoListId = SYSTEM_CONFIG.TASKS.TODO_LIST_ID;
  const recurringListId = SYSTEM_CONFIG.TASKS.RECURRING_LIST_ID;
  
  const rawTasks = [];
  [importerListId, todoListId, recurringListId].forEach(listId => {
    let pageToken;
    do {
      const response = executeWithRetry(() => Tasks.Tasks.list(listId, { showCompleted: false, showHidden: false, showAssigned: true, maxResults: 100, pageToken: pageToken }));
      const items = response.items || [];
      items.forEach(t => rawTasks.push({ id: t.id, title: t.title, due: t.due, updated: t.updated || "", notes: t.notes || "", status: t.status }));
      pageToken = response.nextPageToken;
    } while (pageToken);
  });

  const payload = {
    currentTime: new Date().toISOString(),
    goals: getSystemGoals(),
    allTasksContext: rawTasks.map(t => {
       const parsed = parseTaskNotes(t.notes);
       let metadata = parsed.metadata || {};
       let cleanNotes = parsed.baseNotes.replace(/\[DEADLINE:[^\]]*\]\s*\|\s*\[DURATION:[^\]]*\]\s*\|\s*\[GOAL:[^\]]*\]/g, "");
       cleanNotes = cleanNotes.replace(/\[DURATION:[^\]]*\]\s*\|\s*\[GOAL:[^\]]*\]/g, "");
       return { 
         title: t.title, 
         due: t.due, 
         updated: t.updated,
         notes: cleanNotes.trim(),
         category_path: metadata.category_path || "N/A",
         goal: metadata.goal || "N/A",
         duration: metadata.duration || "N/A"
       };
    })
  };

  let systemPrompt = "";
  try {
     const fileId = SYSTEM_CONFIG.DOCS.TASK_MASTER_MONTHLY_PROMPT_ID;
     if (!fileId) throw new Error("TASK_MASTER_MONTHLY_PROMPT_ID is not configured in SYSTEM_CONFIG.");
     const file = DriveApp.getFileById(fileId);
     const mimeType = file.getMimeType();
     let text = "";
     if (mimeType === MimeType.GOOGLE_DOCS) {
       text = DocumentApp.openById(fileId).getBody().getText();
     } else if (mimeType === MimeType.PLAIN_TEXT || mimeType === "text/plain" || mimeType === "text/markdown") {
       text = file.getBlob().getDataAsString();
     } else {
       throw new Error(`Unsupported MIME type: ${mimeType}`);
     }
     systemPrompt = processPromptText(text);
  } catch(e) {
     console.error("Failed to load 28-Day prompt from Drive:", e.message);
     return;
  }
  
  const payloadStr = JSON.stringify(payload);
  // Use 3.7 Flash for hybrid reasoning, fallback to Pro then Flash Lite if needed
  const modelsToTry = [
    SYSTEM_CONFIG.SECRETS.GEMINI_MODEL_PRO, 
    SYSTEM_CONFIG.SECRETS.GEMINI_MODEL_FALLBACK_PRO || "gemini-pro-latest", 
    SYSTEM_CONFIG.SECRETS.GEMINI_MODEL_FLASH_LITE
  ];
  
  let result = null;
  let finalModelUsed = modelsToTry[0];
  
  for (const currentModel of modelsToTry) {
    if (!currentModel) continue;
    finalModelUsed = currentModel;
    console.log(`Executing 28-Day Review via ${currentModel}...`);
    
    result = callGemini(payloadStr, currentModel, systemPrompt, null, true);
    if (!result.error) {
      break;
    }
    console.warn(`28-Day Review failed with ${currentModel}:`, result.error);
  }

  if (!result || result.error) {
      const errMsg = "28-Day Review failed after all attempts.";
      console.error(errMsg);
      throw new Error(errMsg);
  }
  
  let markdownReport = result.text;
  markdownReport += `\n\n---\n*Report dynamically generated by ${finalModelUsed}*`;
  
  write28DayReport(markdownReport);
  console.log("28-Day Review Complete. Pruning Report generated.");
}

/**
 * Writes the generated markdown report to the designated Google Drive file.
 *
 * @param {string} markdownStr The markdown content of the 28-Day report.
 * @returns {string|null} The URL of the updated or created file, or null if it fails.
 */
function write28DayReport(markdownStr) {
  const rootFolderId = SYSTEM_CONFIG.ROOTS.WORKSPACE_FOLDER_ID;
  const rootFolder = DriveApp.getFolderById(rootFolderId);
  const exportFolders = rootFolder.getFoldersByName("exports");
  const folder = exportFolders.hasNext() ? exportFolders.next() : rootFolder;
  
  const suffix = IS_CE_ENV ? " (CE)" : " (Private)";

  // 1. Create a dated historical copy in the archives subfolder
  try {
    const archiveFolders = folder.getFoldersByName("archives");
    const archiveFolder = archiveFolders.hasNext() ? archiveFolders.next() : folder.createFolder("archives");
    
    const timestamp = Utilities.formatDate(new Date(), "Europe/London", "yyyy-MM-dd");
    const datedFileName = `TS - Task Master > 28 Day Strategic Pruning - ${timestamp}${suffix}.md`;
    archiveFolder.createFile(datedFileName, markdownStr, MimeType.PLAIN_TEXT);
    console.log(`Created dated backup: ${datedFileName}`);
  } catch(e) {
    console.warn("Failed to create dated backup:", e.message);
  }

  // 2. Update the fixed file (for other scripts to read)
  let fileId = SYSTEM_CONFIG.GENERATED_OUTPUTS.DAY_28_STRATEGIC;
  let file = null;

  if (fileId) {
    try {
      file = DriveApp.getFileById(fileId);
    } catch (e) {
      console.warn("File not found or no permission for ID. Falling back to creation...", e.message);
      fileId = null;
    }
  }

  if (!fileId || !file) {
     console.error("Missing or invalid ID for DAY_28_STRATEGIC. Creating fixed file...");
     const fileName = `TS - Task Master > 28 Day Strategic Pruning${suffix}.md`;
     file = folder.createFile(fileName, markdownStr, MimeType.PLAIN_TEXT);
     console.warn(`CREATED NEW FIXED FILE! Update config: ${file.getId()}`);
     return file.getUrl();
  }

  try {
     file.setContent(markdownStr);
     return file.getUrl();
  } catch(e) {
     console.error("Failed to write 28-Day Report:", e.message);
     return null;
  }
}

/**
 * Trigger wrapper for the 28-Day Strategic Review.
 * Executes the review every 28 days based on a base reference date.
 *
 * @returns {void}
 */
function monthlyReviewTriggerWrapper() {
  const lock = LockService.getScriptLock();
  if (!lock.tryLock(10000)) {
    console.warn("Could not acquire script lock. Monthly review is likely running.");
    return;
  }
  try {
    const now = new Date();
    const currentHour = now.getHours();
    
    // Set reference to May 10, 2026 (which is a Sunday)
    const baseDate = new Date(Date.UTC(2026, 4, 10)); // Month is 0-indexed, 4 = May
    
    // Calculate days difference (ignoring hours/minutes to avoid DST drift)
    const nowUtc = new Date(Date.UTC(now.getFullYear(), now.getMonth(), now.getDate()));
    const diffTimeMs = nowUtc.getTime() - baseDate.getTime();
    const diffDays = Math.round(diffTimeMs / (1000 * 60 * 60 * 24));
    
    const scriptProps = PropertiesService.getScriptProperties();
    const lastRunKey = "LAST_RUN_28_DAY";
    const todayStr = Utilities.formatDate(nowUtc, "UTC", "yyyy-MM-dd");
    
    if (diffDays >= 0 && diffDays % 28 === 0) {
      const lastRunStr = scriptProps.getProperty(lastRunKey);
      if (lastRunStr !== todayStr) {
        if (currentHour >= 9) {
          console.log("Executing 28-Day Strategic Review...");
          runMonthlyReview();
          scriptProps.setProperty(lastRunKey, todayStr);
        } else {
          console.log(`Waiting for 09:00 to run 28-Day review. Current hour: ${currentHour}.`);
        }
      } else {
        console.log(`28-Day review already ran successfully today (${todayStr}).`);
      }
    } else {
      console.log(`Skipping 28-Day review. Days since base (May 10): ${diffDays}, Hour: ${currentHour}.`);
    }
  } finally {
    lock.releaseLock();
  }
}


// ==========================================
// SECTION 3: 84-DAY QUARTERLY STRATEGIC REFLECTION
// ==========================================

/**
 * @file src/Code_84DayReview.js
 * @description Generates the 84-Day Strategic Reflection Report focusing on macro-trajectory and goal alignment.
 */

function runQuarterlyReview() {
  const importerListId = SYSTEM_CONFIG.TASKS.IMPORTER_LIST_ID;
  const todoListId = SYSTEM_CONFIG.TASKS.TODO_LIST_ID;
  const recurringListId = SYSTEM_CONFIG.TASKS.RECURRING_LIST_ID;
  
  const rawTasks = [];
  [importerListId, todoListId, recurringListId].forEach(listId => {
    let pageToken;
    do {
      const response = executeWithRetry(() => Tasks.Tasks.list(listId, { showCompleted: false, showHidden: false, showAssigned: true, maxResults: 100, pageToken: pageToken }));
      const items = response.items || [];
      items.forEach(t => rawTasks.push({ id: t.id, title: t.title, due: t.due, notes: t.notes || "", status: t.status }));
      pageToken = response.nextPageToken;
    } while (pageToken);
  });

  let recentReflections = "";
  try {
     recentReflections += getSafeDocText(SYSTEM_CONFIG.DOCS.VANTAGE_LOG_ID) + "\n\n";
     recentReflections += getSafeDocText(SYSTEM_CONFIG.DOCS.RECENT_REFLECTIONS_ID);
  } catch(e) {
     console.warn("Could not fetch reflection logs:", e.message);
  }

  const payload = {
    currentTime: new Date().toISOString(),
    goals: getSystemGoals(),
    recentReflections: recentReflections,
    allTasksContext: rawTasks.map(t => {
       const parsed = parseTaskNotes(t.notes);
       let metadata = parsed.metadata || {};
       let cleanNotes = parsed.baseNotes.replace(/\[DEADLINE:[^\]]*\]\s*\|\s*\[DURATION:[^\]]*\]\s*\|\s*\[GOAL:[^\]]*\]/g, "");
       cleanNotes = cleanNotes.replace(/\[DURATION:[^\]]*\]\s*\|\s*\[GOAL:[^\]]*\]/g, "");
       return { 
         title: t.title, 
         due: t.due, 
         notes: cleanNotes.trim(),
         category_path: metadata.category_path || "N/A",
         goal: metadata.goal || "N/A",
         duration: metadata.duration || "N/A"
       };
    })
  };

  let systemPrompt = "";
  try {
     const fileId = SYSTEM_CONFIG.DOCS.TASK_MASTER_QUARTERLY_PROMPT_ID;
     if (!fileId) throw new Error("TASK_MASTER_QUARTERLY_PROMPT_ID is not configured in SYSTEM_CONFIG.");
     systemPrompt = getSafeDocText(fileId);
     if (!systemPrompt) throw new Error("System prompt is empty or could not be loaded.");
  } catch(e) {
     console.error("Failed to load 84-Day prompt from Drive:", e.message);
     return;
  }
  
  const payloadStr = JSON.stringify(payload);
  // Use 3.7 Flash for hybrid reasoning, fallback to Pro then Flash Lite if needed
  const modelsToTry = [
    SYSTEM_CONFIG.SECRETS.GEMINI_MODEL_PRO, 
    SYSTEM_CONFIG.SECRETS.GEMINI_MODEL_FALLBACK_PRO || "gemini-pro-latest", 
    SYSTEM_CONFIG.SECRETS.GEMINI_MODEL_FLASH_LITE
  ];
  
  let result = null;
  let finalModelUsed = modelsToTry[0];
  
  for (const currentModel of modelsToTry) {
    if (!currentModel) continue;
    finalModelUsed = currentModel;
    console.log(`Executing 84-Day Review via ${currentModel}...`);
    
    result = callGemini(payloadStr, currentModel, systemPrompt, null, true);
    if (!result.error) {
      break;
    }
    console.warn(`84-Day Review failed with ${currentModel}:`, result.error);
  }

  if (!result || result.error) {
      const errMsg = "84-Day Review failed after all attempts.";
      console.error(errMsg);
      throw new Error(errMsg);
  }
  
  let markdownReport = result.text;
  markdownReport += `\n\n---\n*Report dynamically generated by ${finalModelUsed}*`;
  
  write84DayReport(markdownReport);
  console.log("84-Day Review Complete. Strategic Reflection Report generated.");
}

function write84DayReport(markdownStr) {
  const rootFolderId = SYSTEM_CONFIG.ROOTS.WORKSPACE_FOLDER_ID;
  const rootFolder = DriveApp.getFolderById(rootFolderId);
  const exportFolders = rootFolder.getFoldersByName("exports");
  const folder = exportFolders.hasNext() ? exportFolders.next() : rootFolder;
  
  const suffix = IS_CE_ENV ? " (CE)" : " (Private)";

  // 1. Create a dated historical copy in the archives subfolder
  try {
    const archiveFolders = folder.getFoldersByName("archives");
    const archiveFolder = archiveFolders.hasNext() ? archiveFolders.next() : folder.createFolder("archives");
    
    const timestamp = Utilities.formatDate(new Date(), "Europe/London", "yyyy-MM-dd");
    const datedFileName = `TS - Task Master > 84 Day Strategic Pruning - ${timestamp}${suffix}.md`;
    archiveFolder.createFile(datedFileName, markdownStr, MimeType.PLAIN_TEXT);
    console.log(`Created dated backup: ${datedFileName}`);
  } catch(e) {
    console.warn("Failed to create dated backup:", e.message);
  }

  // 2. Update the fixed file (for other scripts to read)
  let fileId = SYSTEM_CONFIG.GENERATED_OUTPUTS.DAY_84_STRATEGIC;
  let file = null;

  if (fileId) {
    try {
      file = DriveApp.getFileById(fileId);
    } catch (e) {
      console.warn("File not found or no permission for ID. Falling back to creation...", e.message);
      fileId = null;
    }
  }

  if (!fileId || !file) {
     console.error("Missing or invalid ID for DAY_84_STRATEGIC. Creating file...");
     const fileName = `TS - Task Master > 84 Day Strategic Pruning${suffix}.md`;
     file = folder.createFile(fileName, markdownStr, MimeType.PLAIN_TEXT);
     console.warn(`CREATED NEW FILE! Update config: ${file.getId()}`);
     return file.getUrl();
  }

  try {
     file.setContent(markdownStr);
     return file.getUrl();
  } catch(e) {
     console.error("Failed to update DAY_84_STRATEGIC ID:", e.message);
     return null;
  }
}

function quarterlyReviewTriggerWrapper() {
  const lock = LockService.getScriptLock();
  if (!lock.tryLock(10000)) {
    console.warn("Could not acquire script lock. Quarterly review is likely running.");
    return;
  }
  try {
    const now = new Date();
    const currentHour = now.getHours();
    
    // Set reference to May 10, 2026 (which is a Sunday)
    const baseDate = new Date(Date.UTC(2026, 4, 10)); // Month is 0-indexed, 4 = May
    
    // Calculate days difference (ignoring hours/minutes to avoid DST drift)
    const nowUtc = new Date(Date.UTC(now.getFullYear(), now.getMonth(), now.getDate()));
    const diffTime = nowUtc.getTime() - baseDate.getTime();
    const diffDays = Math.round(diffTime / (1000 * 60 * 60 * 24));
    
    const scriptProps = PropertiesService.getScriptProperties();
    const lastRunKey = "LAST_RUN_84_DAY";
    const todayStr = Utilities.formatDate(nowUtc, "UTC", "yyyy-MM-dd");
    
    if (diffDays >= 0 && diffDays % 84 === 0) {
      const lastRunStr = scriptProps.getProperty(lastRunKey);
      if (lastRunStr !== todayStr) {
        if (currentHour >= 9) {
          console.log("Executing 84-Day Strategic Review...");
          runQuarterlyReview();
          scriptProps.setProperty(lastRunKey, todayStr);
        } else {
          console.log(`Waiting for 09:00 to run 84-Day review. Current hour: ${currentHour}.`);
        }
      } else {
        console.log(`84-Day review already ran successfully today (${todayStr}).`);
      }
    } else {
      console.log(`Skipping 84-Day review. Days since base (May 10): ${diffDays}, Hour: ${currentHour}.`);
    }
  } finally {
    lock.releaseLock();
  }
}

