/**
 * @file src/Code_84DayReview.js
 * @description Generates the 84-Day Strategic Reflection Report focusing on macro-trajectory and goal alignment.
 */

function runQuarterlyReview() {
  const importerListId = SYSTEM_CONFIG.TASKS.IMPORTER_LIST_ID;
  const todoListId = SYSTEM_CONFIG.TASKS.TODO_LIST_ID;
  const recurringListId = SYSTEM_CONFIG.TASKS.RECURRING_LIST_ID;
  
  const rawTasks = [];
  [importerListId, todoListId, recurringListId].forEach(listId => {
    let pageToken;
    do {
      const response = executeWithRetry(() => Tasks.Tasks.list(listId, { showCompleted: false, showHidden: false, showAssigned: true, maxResults: 100, pageToken: pageToken }));
      const items = response.items || [];
      items.forEach(t => rawTasks.push({ id: t.id, title: t.title, due: t.due, notes: t.notes || "", status: t.status }));
      pageToken = response.nextPageToken;
    } while (pageToken);
  });

  let recentReflections = "";
  try {
     recentReflections += getSafeDocText(SYSTEM_CONFIG.DOCS.VANTAGE_LOG_ID) + "\n\n";
     recentReflections += getSafeDocText(SYSTEM_CONFIG.DOCS.RECENT_REFLECTIONS_ID);
  } catch(e) {
     console.warn("Could not fetch reflection logs:", e.message);
  }

  const payload = {
    currentTime: new Date().toISOString(),
    goals: getSystemGoals(),
    recentReflections: recentReflections,
    allTasksContext: rawTasks.map(t => {
       const parsed = parseTaskNotes(t.notes);
       let metadata = parsed.metadata || {};
       let cleanNotes = parsed.baseNotes.replace(/\[DEADLINE:[^\]]*\]\s*\|\s*\[DURATION:[^\]]*\]\s*\|\s*\[GOAL:[^\]]*\]/g, "");
       cleanNotes = cleanNotes.replace(/\[DURATION:[^\]]*\]\s*\|\s*\[GOAL:[^\]]*\]/g, "");
       return { 
         title: t.title, 
         due: t.due, 
         notes: cleanNotes.trim(),
         category_path: metadata.category_path || "N/A",
         goal: metadata.goal || "N/A",
         duration: metadata.duration || "N/A"
       };
    })
  };

  let systemPrompt = "";
  try {
     const fileId = SYSTEM_CONFIG.DOCS.TASK_MASTER_QUARTERLY_PROMPT_ID;
     if (!fileId) throw new Error("TASK_MASTER_QUARTERLY_PROMPT_ID is not configured in SYSTEM_CONFIG.");
     systemPrompt = getSafeDocText(fileId);
     if (!systemPrompt) throw new Error("System prompt is empty or could not be loaded.");
  } catch(e) {
     console.error("Failed to load 84-Day prompt from Drive:", e.message);
     return;
  }
  
  const payloadStr = JSON.stringify(payload);
  const apiKey = SYSTEM_CONFIG.SECRETS.GEMINI_API_KEY;
  // Use Pro model for deep strategic reasoning, fallback to Flash if needed
  const modelsToTry = [SYSTEM_CONFIG.SECRETS.GEMINI_MODEL_PRO, SYSTEM_CONFIG.SECRETS.GEMINI_MODEL_FLASH];
  
  let result = null;
  let finalModelUsed = modelsToTry[0];
  
  for (const currentModel of modelsToTry) {
    if (!currentModel) continue;
    finalModelUsed = currentModel;
    console.log(`Executing 84-Day Review via ${currentModel}...`);
    
    result = callGemini(payloadStr, currentModel, systemPrompt, null, true);
    if (!result.error) {
      break;
    }
    console.warn(`84-Day Review failed with ${currentModel}:`, result.error);
  }

  if (!result || result.error) {
      const errMsg = "84-Day Review failed after all attempts.";
      console.error(errMsg);
      throw new Error(errMsg);
  }
  
  let markdownReport = result.text;
  markdownReport += `\n\n---\n*Report dynamically generated by ${finalModelUsed}*`;
  
  write84DayReport(markdownReport);
  console.log("84-Day Review Complete. Strategic Reflection Report generated.");
}

function write84DayReport(markdownStr) {
  const fileId = SYSTEM_CONFIG.GENERATED_OUTPUTS.DAY_84_STRATEGIC;
  if (!fileId) {
     console.error("Missing ID for DAY_84_STRATEGIC. Creating file...");
     const suffix = IS_PMT_ENV ? " (PMT)" : " (Private)";
     const fileName = `TS - Task Master > 84 Day Strategic Reflection${suffix}.md`;
     const file = DriveApp.getFolderById(SYSTEM_CONFIG.ROOTS.WORKSPACE_FOLDER_ID).createFile(fileName, markdownStr, MimeType.PLAIN_TEXT);
     console.warn(`CREATED NEW FILE! Update config: ${file.getId()}`);
     return file.getUrl();
  }
  try {
     const file = DriveApp.getFileById(fileId);
     file.setContent(markdownStr);
     return file.getUrl();
  } catch(e) {
     console.error("Failed to write 84-Day Report:", e.message);
     return null;
  }
}

function quarterlyReviewTriggerWrapper() {
  const lock = LockService.getScriptLock();
  if (!lock.tryLock(10000)) {
    console.warn("Could not acquire script lock. Quarterly review is likely running.");
    return;
  }
  try {
    const now = new Date();
    const currentHour = now.getHours();
    
    // Set reference to May 10, 2026 (which is a Sunday)
    const baseDate = new Date(Date.UTC(2026, 4, 10)); // Month is 0-indexed, 4 = May
    
    // Calculate days difference (ignoring hours/minutes to avoid DST drift)
    const nowUtc = new Date(Date.UTC(now.getFullYear(), now.getMonth(), now.getDate()));
    const diffTime = nowUtc.getTime() - baseDate.getTime();
    const diffDays = Math.round(diffTime / (1000 * 60 * 60 * 24));
    
    const scriptProps = PropertiesService.getScriptProperties();
    const lastRunKey = "LAST_RUN_84_DAY";
    const todayStr = Utilities.formatDate(nowUtc, "UTC", "yyyy-MM-dd");
    
    if (diffDays >= 0 && diffDays % 84 === 0) {
      const lastRunStr = scriptProps.getProperty(lastRunKey);
      if (lastRunStr !== todayStr) {
        if (currentHour >= 9) {
          console.log("Executing 84-Day Strategic Review...");
          runQuarterlyReview();
          scriptProps.setProperty(lastRunKey, todayStr);
        } else {
          console.log(`Waiting for 09:00 to run 84-Day review. Current hour: ${currentHour}.`);
        }
      } else {
        console.log(`84-Day review already ran successfully today (${todayStr}).`);
      }
    } else {
      console.log(`Skipping 84-Day review. Days since base (May 10): ${diffDays}, Hour: ${currentHour}.`);
    }
  } finally {
    lock.releaseLock();
  }
}
