/**
 * @file src/Code_WeeklyReview.js
 * @description Generates the 7-Day Roadmap by sweeping the backlog and aligning with weekly calendar capacity.
 */

function runWeeklyReview() {
  const importerListId = SYSTEM_CONFIG.TASKS.IMPORTER_LIST_ID;
  const todoListId = SYSTEM_CONFIG.TASKS.TODO_LIST_ID;
  const recurringListId = SYSTEM_CONFIG.TASKS.RECURRING_LIST_ID;
  
  const rawTasks = [];
  [importerListId, todoListId, recurringListId].forEach(listId => {
    let pageToken;
    do {
      try {
        const response = Tasks.Tasks.list(listId, { showCompleted: false, showHidden: false, showAssigned: true, maxResults: 100, pageToken: pageToken });
        const items = response.items || [];
        items.forEach(t => rawTasks.push({ id: t.id, title: t.title, due: t.due, notes: t.notes || "", status: t.status }));
        pageToken = response.nextPageToken;
      } catch (e) {
        console.error(`runWeeklyReview Error reading list ${listId}: ${e.message}`);
        pageToken = undefined;
      }
    } while (pageToken);
  });

  if (rawTasks.length === 0) {
     console.error("runWeeklyReview: No tasks found. Aborting to prevent generating an empty plan.");
     return;
  }

  const payload = {
    currentTime: new Date().toISOString(),
    capacity7Days: getCalendarCapacity7Days(),
    goals: getSystemGoals(),
    allTasksContext: rawTasks.map(t => {
       let cleanNotes = t.notes;
       let metadata = {};
       const metaSplit = cleanNotes.split('---SYSTEM_METADATA---');
       if (metaSplit.length > 1) {
          try {
             metadata = JSON.parse(metaSplit[1].trim());
          } catch(e) {}
       }
       cleanNotes = metaSplit[0].replace(/\[DEADLINE:[^\]]*\]\s*\|\s*\[DURATION:[^\]]*\]\s*\|\s*\[GOAL:[^\]]*\]/g, "");
       cleanNotes = cleanNotes.replace(/\[DURATION:[^\]]*\]\s*\|\s*\[GOAL:[^\]]*\]/g, "");
       return { 
         id: t.id,
         title: t.title, 
         due: t.due, 
         notes: cleanNotes.trim(),
         category_path: metadata.category_path || "N/A",
         goal: metadata.goal || "N/A",
         duration: metadata.duration || "N/A"
       };
    })
  };

  let systemPrompt = "";
  try {
     const fileId = SYSTEM_CONFIG.DOCS.TASK_MASTER_WEEKLY_PROMPT_ID;
     if (!fileId) throw new Error("TASK_MASTER_WEEKLY_PROMPT_ID is not configured in SYSTEM_CONFIG.");
     const file = DriveApp.getFileById(fileId);
     systemPrompt = processPromptText(file.getBlob().getDataAsString());
  } catch(e) {
     console.error("Failed to load 7-Day prompt from Drive:", e.message);
     return;
  }
  
  const payloadStr = JSON.stringify(payload);
  const apiKey = SYSTEM_CONFIG.SECRETS.GEMINI_API_KEY;
  // Use Pro model for heavy 7-day reasoning, fallback to Flash if needed
  const modelsToTry = [SYSTEM_CONFIG.SECRETS.GEMINI_MODEL_PRO, SYSTEM_CONFIG.SECRETS.GEMINI_MODEL_FLASH];
  
  let result = null;
  let finalModelUsed = modelsToTry[0];
  
  for (const currentModel of modelsToTry) {
    if (!currentModel) continue;
    finalModelUsed = currentModel;
    console.log(`Executing 7-Day Review via ${currentModel}...`);
    
    result = callGemini(payloadStr, currentModel, systemPrompt, null, true);
    if (!result.error) {
      break;
    }
    console.warn(`7-Day Review failed with ${currentModel}:`, result.error);
  }

  if (!result || result.error) {
      console.error("7-Day Review failed after all attempts.");
      return;
  }
  
  let markdownReport = result.text;
  const timestamp = new Date().toLocaleString("en-GB", { timeZone: "Europe/London" });
  markdownReport += `\n\n---\n*Report dynamically generated by ${finalModelUsed} on ${timestamp}*`;
  
  write7DayRoadmap(markdownReport);
  console.log("7-Day Review Complete. Roadmap generated.");
}

function getCalendarCapacity7Days() {
  const calendarId = "primary";
  const now = new Date();
  const nextWeek = new Date(now.getTime() + (7 * 24 * 60 * 60 * 1000));
  
  try {
    const capacityMap = {};
    for (let i = 0; i < 7; i++) {
      const d = new Date(now.getTime() + (i * 24 * 60 * 60 * 1000));
      const dateKey = Utilities.formatDate(d, "Europe/London", "yyyy-MM-dd");
      capacityMap[dateKey] = { busyHours: 0, availableHours: 12 };
    }
    
    let pageToken;
    do {
      const response = Calendar.Events.list(calendarId, {
        timeMin: now.toISOString(),
        timeMax: nextWeek.toISOString(),
        singleEvents: true,
        maxResults: 250,
        pageToken: pageToken
      });
      
      const items = response.items || [];
      items.forEach(e => {
        // Skip Free events and All-Day events
        if (e.transparency === 'transparent') return;
        if (e.start.date) return; // All-day events only have a date, not dateTime
        
        const startTime = new Date(e.start.dateTime);
        const endTime = new Date(e.end.dateTime);
        const durationHours = (endTime - startTime) / (1000 * 60 * 60);
        const dateKey = Utilities.formatDate(startTime, "Europe/London", "yyyy-MM-dd");
        
        if (capacityMap[dateKey]) {
          capacityMap[dateKey].busyHours += durationHours;
          capacityMap[dateKey].availableHours = Math.max(0, 12 - capacityMap[dateKey].busyHours);
        }
      });
      pageToken = response.nextPageToken;
    } while (pageToken);
    
    return capacityMap;
  } catch (e) {
    console.error("Failed to fetch calendar capacity: " + e.message);
    return { error: "Failed to fetch calendar capacity" };
  }
}

function write7DayRoadmap(markdownStr) {
  const folderId = SYSTEM_CONFIG.ROOTS.WORKSPACE_FOLDER_ID;
  const suffix = isPmtAccount() ? " (PMT)" : " (Private)";
  const fileName = `TS - Task Master > 7 Day Roadmap${suffix}.md`;
  try {
     const folder = DriveApp.getFolderById(folderId);
     const files = folder.getFilesByName(fileName);
     let file;
     if (files.hasNext()) {
        file = files.next();
        file.setContent(markdownStr);
     } else {
        file = folder.createFile(fileName, markdownStr, MimeType.PLAIN_TEXT);
     }
     return file.getUrl();
  } catch(e) {
     console.error("Failed to write 7-Day Roadmap:", e.message);
     return null;
  }
}

function weeklyReviewTriggerWrapper() {
  const currentDay = new Date().getDay(); // 0 is Sunday, 5 is Friday
  // Execute only on Sunday at 9:00
  const currentHour = new Date().getHours();
  
  if (currentDay === 0 && [9].includes(currentHour)) {
    console.log("Executing weekly 7-Day Review...");
    try {
      runTaskMasterEngine(); // Pre-clean
    } catch(e) {}
    runWeeklyReview();
  } else {
    console.log(`Skipping weekly review (Day: ${currentDay}, Hour: ${currentHour}).`);
  }
}
