/**
 * @file src/Code_28DayReview.js
 * @description Generates the 28-Day Strategic Pruning Report by aggressively pruning the backlog and aligning tasks with overarching goals.
 *
 * @version 1.0.0
 * @last_modified 2024-07-28
 * @modified_by Jules
 *
 * @changelog
 * - 1.0.0: Added standardized JSDoc headers and variable naming.
 */

/**
 * Generates the 28-Day Strategic Pruning Report by aggregating tasks,
 * calling the AI model for review, and saving the output to Google Drive.
 *
 * @returns {void}
 */
function runMonthlyReview() {
  const importerListId = SYSTEM_CONFIG.TASKS.IMPORTER_LIST_ID;
  const todoListId = SYSTEM_CONFIG.TASKS.TODO_LIST_ID;
  const recurringListId = SYSTEM_CONFIG.TASKS.RECURRING_LIST_ID;
  
  const rawTasks = [];
  [importerListId, todoListId, recurringListId].forEach(listId => {
    let pageToken;
    do {
      try {
        const response = Tasks.Tasks.list(listId, { showCompleted: false, showHidden: false, showAssigned: true, maxResults: 100, pageToken: pageToken });
        const items = response.items || [];
        items.forEach(t => rawTasks.push({ id: t.id, title: t.title, due: t.due, updated: t.updated || "", notes: t.notes || "", status: t.status }));
        pageToken = response.nextPageToken;
      } catch (e) {
        pageToken = undefined;
      }
    } while (pageToken);
  });

  const payload = {
    currentTime: new Date().toISOString(),
    goals: getSystemGoals(),
    allTasksContext: rawTasks.map(t => {
       const parsed = parseTaskNotes(t.notes);
       let metadata = parsed.metadata || {};
       let cleanNotes = parsed.baseNotes.replace(/\[DEADLINE:[^\]]*\]\s*\|\s*\[DURATION:[^\]]*\]\s*\|\s*\[GOAL:[^\]]*\]/g, "");
       cleanNotes = cleanNotes.replace(/\[DURATION:[^\]]*\]\s*\|\s*\[GOAL:[^\]]*\]/g, "");
       return { 
         title: t.title, 
         due: t.due, 
         updated: t.updated,
         notes: cleanNotes.trim(),
         category_path: metadata.category_path || "N/A",
         goal: metadata.goal || "N/A",
         duration: metadata.duration || "N/A"
       };
    })
  };

  let systemPrompt = "";
  try {
     const fileId = SYSTEM_CONFIG.DOCS.TASK_MASTER_MONTHLY_PROMPT_ID;
     if (!fileId) throw new Error("TASK_MASTER_MONTHLY_PROMPT_ID is not configured in SYSTEM_CONFIG.");
     const file = DriveApp.getFileById(fileId);
     const mimeType = file.getMimeType();
     let text = "";
     if (mimeType === MimeType.GOOGLE_DOCS) {
       text = DocumentApp.openById(fileId).getBody().getText();
     } else if (mimeType === MimeType.PLAIN_TEXT || mimeType === "text/plain") {
       text = file.getBlob().getDataAsString();
     } else {
       throw new Error(`Unsupported MIME type: ${mimeType}`);
     }
     systemPrompt = processPromptText(text);
  } catch(e) {
     console.error("Failed to load 28-Day prompt from Drive:", e.message);
     return;
  }
  
  const payloadStr = JSON.stringify(payload);
  const apiKey = SYSTEM_CONFIG.SECRETS.GEMINI_API_KEY;
  // Use Pro model for heavy pruning reasoning, fallback to Flash if needed
  const modelsToTry = [SYSTEM_CONFIG.SECRETS.GEMINI_MODEL_PRO, SYSTEM_CONFIG.SECRETS.GEMINI_MODEL_FLASH];
  
  let result = null;
  let finalModelUsed = modelsToTry[0];
  
  for (const currentModel of modelsToTry) {
    if (!currentModel) continue;
    finalModelUsed = currentModel;
    console.log(`Executing 28-Day Review via ${currentModel}...`);
    
    result = callGemini(payloadStr, currentModel, systemPrompt, null, true);
    if (!result.error) {
      break;
    }
    console.warn(`28-Day Review failed with ${currentModel}:`, result.error);
  }

  if (!result || result.error) {
      console.error("28-Day Review failed after all attempts.");
      return;
  }
  
  let markdownReport = result.text;
  markdownReport += `\n\n---\n*Report dynamically generated by ${finalModelUsed}*`;
  
  write28DayReport(markdownReport);
  console.log("28-Day Review Complete. Pruning Report generated.");
}

/**
 * Writes the generated markdown report to the designated Google Drive file.
 *
 * @param {string} markdownStr The markdown content of the 28-Day report.
 * @returns {string|null} The URL of the updated or created file, or null if it fails.
 */
function write28DayReport(markdownStr) {
  const fileId = SYSTEM_CONFIG.GENERATED_OUTPUTS.DAY_28_STRATEGIC;
  if (!fileId) {
     console.error("Missing ID for DAY_28_STRATEGIC. Creating file...");
     const suffix = IS_PMT_ENV ? " (PMT)" : " (Private)";
     const fileName = `TS - Task Master > 28 Day Strategic Pruning${suffix}.md`;
     const file = DriveApp.getFolderById(SYSTEM_CONFIG.ROOTS.WORKSPACE_FOLDER_ID).createFile(fileName, markdownStr, MimeType.PLAIN_TEXT);
     console.warn(`CREATED NEW FILE! Update config: ${file.getId()}`);
     return file.getUrl();
  }
  try {
     const file = DriveApp.getFileById(fileId);
     file.setContent(markdownStr);
     return file.getUrl();
  } catch(e) {
     console.error("Failed to write 28-Day Report:", e.message);
     return null;
  }
}

/**
 * Trigger wrapper for the 28-Day Strategic Review.
 * Executes the review every 28 days based on a base reference date.
 *
 * @returns {void}
 */
function monthlyReviewTriggerWrapper() {
  const now = new Date();
  const currentHour = now.getHours();
  
  // Set reference to May 10, 2026 (which is a Sunday)
  const baseDate = new Date(Date.UTC(2026, 4, 10)); // Month is 0-indexed, 4 = May
  
  // Calculate days difference (ignoring hours/minutes to avoid DST drift)
  const nowUtc = new Date(Date.UTC(now.getFullYear(), now.getMonth(), now.getDate()));
  const diffTimeMs = nowUtc.getTime() - baseDate.getTime();
  const diffDays = Math.round(diffTimeMs / (1000 * 60 * 60 * 24));
  
  // Execute every 28 days (diffDays % 28 === 0) at 9:00
  if (diffDays >= 0 && diffDays % 28 === 0 && [9].includes(currentHour)) {
    console.log("Executing 28-Day Strategic Review...");
    try {
      runTaskMasterEngine(); // Pre-clean
    } catch(e) {}
    runMonthlyReview();
  } else {
    console.log(`Skipping 28-Day review. Days since base (May 10): ${diffDays}, Hour: ${currentHour}.`);
  }
}
