/**
 * @file src/Code_84DayReview.js
 * @description Generates the 84-Day Strategic Reflection Report focusing on macro-trajectory and goal alignment.
 */

function runQuarterlyReview() {
  const importerListId = SYSTEM_CONFIG.TASKS.IMPORTER_LIST_ID;
  const todoListId = SYSTEM_CONFIG.TASKS.TODO_LIST_ID;
  const recurringListId = SYSTEM_CONFIG.TASKS.RECURRING_LIST_ID;
  
  const rawTasks = [];
  [importerListId, todoListId, recurringListId].forEach(listId => {
    let pageToken;
    do {
      try {
        const response = Tasks.Tasks.list(listId, { showCompleted: false, showHidden: false, showAssigned: true, maxResults: 100, pageToken: pageToken });
        const items = response.items || [];
        items.forEach(t => rawTasks.push({ id: t.id, title: t.title, due: t.due, notes: t.notes || "", status: t.status }));
        pageToken = response.nextPageToken;
      } catch (e) {
        pageToken = undefined;
      }
    } while (pageToken);
  });

  let recentReflections = "";
  try {
     recentReflections += getSafeDocText(SYSTEM_CONFIG.DOCS.VANTAGE_LOG_ID) + "\n\n";
     recentReflections += getSafeDocText(SYSTEM_CONFIG.DOCS.RECENT_REFLECTIONS_ID);
  } catch(e) {
     console.warn("Could not fetch reflection logs:", e.message);
  }

  const payload = {
    currentTime: new Date().toISOString(),
    goals: getSystemGoals(),
    recentReflections: recentReflections,
    allTasksContext: rawTasks.map(t => {
       let cleanNotes = t.notes;
       let metadata = {};
       const metaSplit = cleanNotes.split('---SYSTEM_METADATA---');
       if (metaSplit.length > 1) {
          try {
             metadata = JSON.parse(metaSplit[1].trim());
          } catch(e) {}
       }
       cleanNotes = metaSplit[0].replace(/\[DEADLINE:[^\]]*\]\s*\|\s*\[DURATION:[^\]]*\]\s*\|\s*\[GOAL:[^\]]*\]/g, "");
       cleanNotes = cleanNotes.replace(/\[DURATION:[^\]]*\]\s*\|\s*\[GOAL:[^\]]*\]/g, "");
       return { 
         title: t.title, 
         due: t.due, 
         notes: cleanNotes.trim(),
         category_path: metadata.category_path || "N/A",
         goal: metadata.goal || "N/A",
         duration: metadata.duration || "N/A"
       };
    })
  };

  let systemPrompt = "";
  try {
     const fileId = SYSTEM_CONFIG.DOCS.TASK_MASTER_QUARTERLY_PROMPT_ID;
     if (!fileId) throw new Error("TASK_MASTER_QUARTERLY_PROMPT_ID is not configured in SYSTEM_CONFIG.");
     systemPrompt = getSafeDocText(fileId);
     if (!systemPrompt) throw new Error("System prompt is empty or could not be loaded.");
  } catch(e) {
     console.error("Failed to load 84-Day prompt from Drive:", e.message);
     return;
  }
  
  const payloadStr = JSON.stringify(payload);
  const apiKey = SYSTEM_CONFIG.SECRETS.GEMINI_API_KEY;
  // Use Pro model for deep strategic reasoning, fallback to Flash if needed
  const modelsToTry = [SYSTEM_CONFIG.SECRETS.GEMINI_MODEL_PRO, SYSTEM_CONFIG.SECRETS.GEMINI_MODEL_FLASH];
  
  let responseText = "";
  let success = false;
  let finalModelUsed = modelsToTry[0];
  
  for (const currentModel of modelsToTry) {
    if (success) break;
    if (!currentModel) continue;
    
    finalModelUsed = currentModel;
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${currentModel}:generateContent?key=${apiKey}`;
    
    const payloadReq = {
      contents: [
        { role: "user", parts: [{ text: payloadStr }] }
      ],
      systemInstruction: {
        role: "system",
        parts: [{ text: systemPrompt }]
      },
      generationConfig: {
        temperature: 0.2
      }
    };

    const options = {
      method: "post",
      contentType: "application/json",
      payload: JSON.stringify(payloadReq),
      muteHttpExceptions: true
    };
    
    for (let attempt = 1; attempt <= 2; attempt++) {
      console.log(`Executing 84-Day Review via ${currentModel} (Attempt ${attempt}/2)...`);
      const response = UrlFetchApp.fetch(url, options);
      responseText = response.getContentText();
      
      if (response.getResponseCode() === 200) {
        success = true;
        break;
      } else {
        if (responseText.includes("503") || responseText.includes("429")) {
          Utilities.sleep(Math.pow(2, attempt) * 5000);
        } else {
          break;
        }
      }
    }
  }

  if (!success) {
      console.error("84-Day Review failed after all attempts.");
      return;
  }
  
  const json = JSON.parse(responseText);
  if (json.candidates && json.candidates[0].content && json.candidates[0].content.parts) {
      let markdownReport = json.candidates[0].content.parts[0].text;
      markdownReport += `\n\n---\n*Report dynamically generated by ${finalModelUsed}*`;
      
      write84DayReport(markdownReport);
      console.log("84-Day Review Complete. Strategic Reflection Report generated.");
  }
}

function write84DayReport(markdownStr) {
  const fileId = SYSTEM_CONFIG.GENERATED_OUTPUTS.DAY_84_STRATEGIC;
  if (!fileId) {
     console.error("Missing ID for DAY_84_STRATEGIC. Creating file...");
     const suffix = IS_PMT_ENV ? " (PMT)" : " (Private)";
     const fileName = `TS - Task Master > 84 Day Strategic Reflection${suffix}.md`;
     const file = DriveApp.getFolderById(SYSTEM_CONFIG.ROOTS.WORKSPACE_FOLDER_ID).createFile(fileName, markdownStr, MimeType.PLAIN_TEXT);
     console.warn(`CREATED NEW FILE! Update config: ${file.getId()}`);
     return file.getUrl();
  }
  try {
     const file = DriveApp.getFileById(fileId);
     file.setContent(markdownStr);
     return file.getUrl();
  } catch(e) {
     console.error("Failed to write 84-Day Report:", e.message);
     return null;
  }
}

function quarterlyReviewTriggerWrapper() {
  const now = new Date();
  const currentHour = now.getHours();
  
  // Set reference to May 10, 2026 (which is a Sunday)
  const baseDate = new Date(Date.UTC(2026, 4, 10)); // Month is 0-indexed, 4 = May
  
  // Calculate days difference (ignoring hours/minutes to avoid DST drift)
  const nowUtc = new Date(Date.UTC(now.getFullYear(), now.getMonth(), now.getDate()));
  const diffTime = nowUtc.getTime() - baseDate.getTime();
  const diffDays = Math.round(diffTime / (1000 * 60 * 60 * 24));
  
  // Execute every 84 days (diffDays % 84 === 0) at 9:00
  if (diffDays >= 0 && diffDays % 84 === 0 && [9].includes(currentHour)) {
    console.log("Executing 84-Day Strategic Review...");
    try {
      runTaskMasterEngine(); // Pre-clean
    } catch(e) {}
    runQuarterlyReview();
  } else {
    console.log(`Skipping 84-Day review. Days since base (May 10): ${diffDays}, Hour: ${currentHour}.`);
  }
}
